### ISSUE TITLE
Plugin causes page to disappear in Joomla 5.1

### ISSUE THREAD

**Issue by asabharwal** [TheRichCourt/rc-justified-gallery#7]
I have been using RC Gallery for Joomla 4 without any problem since last year. When I recently tried to add images to the gallery, the entire page disappeared all of a sudden. I was troubleshooting when I realized that removing the {gallery}[path]{/gallery} line brought the page back. It seems to work for 10 images, but as soon as I add even just 5 to the folder and the labels.txt file, the page disappears again. Previously I had about 50, and I have other pages using the RC Gallery. If I try to add to those galleries, the pages will probably disappear, but right now they are still working.  

Joomla has since moved to 5.1, so it may just be a matter of time before RC Gallery stops working altogether unless there is an update to this plugin.  In the meantime, if there is a solution or work-around for this issue, please post it here.  Many thanks!

**Comment by TheRichCourt** [comment]
Thanks. I'll close this and track Joomla 5 compatibility on https://github.com/TheRichCourt/rc-justified-gallery/issues/8
